name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: flask_demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect backend/frontend directories
        id: detect
        run: |
          if [ -d "CRUD_APP/server" ]; then
            echo "BACKEND_DIR=CRUD_APP/server" >> $GITHUB_ENV
            echo "FRONTEND_DIR=CRUD_APP/client" >> $GITHUB_ENV
            echo "REQ_FILE=requirements.txt" >> $GITHUB_ENV
          elif [ -d "CRUD_app_Flask/Server" ]; then
            echo "BACKEND_DIR=CRUD_app_Flask/Server" >> $GITHUB_ENV
            echo "FRONTEND_DIR=CRUD_app_Flask/Client" >> $GITHUB_ENV
            echo "REQ_FILE=requirements.txt" >> $GITHUB_ENV
          else
            echo "Could not detect project layout." >&2
            exit 1
          fi
          echo "Detected BACKEND_DIR=$BACKEND_DIR, FRONTEND_DIR=$FRONTEND_DIR, REQ_FILE=$REQ_FILE"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r "$REQ_FILE"
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Seed backend database
        run: python Playwright_Test_data.py
        working-directory: ${{ env.BACKEND_DIR }}
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password123
          PGDATABASE: flask_demo
          PGPORT: 5432

      - name: Run backend tests
        run: |
          pytest tests/ -v --maxfail=1 --disable-warnings | tee pytest.log
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Upload backend test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: ${{ env.BACKEND_DIR }}/pytest.log
          retention-days: 30

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: test-backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: flask_demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect frontend and backend directories
        run: |
          if [ -d "CRUD_APP/client" ]; then
            echo "FRONTEND_DIR=CRUD_APP/client" >> $GITHUB_ENV
            echo "BACKEND_DIR=CRUD_APP/server" >> $GITHUB_ENV
            echo "REQ_FILE=requirements.txt" >> $GITHUB_ENV
          elif [ -d "CRUD_app_Flask/Client" ]; then
            echo "FRONTEND_DIR=CRUD_app_Flask/Client" >> $GITHUB_ENV
            echo "BACKEND_DIR=CRUD_app_Flask/Server" >> $GITHUB_ENV
            echo "REQ_FILE=requirements.txt" >> $GITHUB_ENV
          else
            echo "Could not detect frontend directory." >&2
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r "$REQ_FILE"
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Seed backend database
        run: python Playwright_Test_data.py
        working-directory: ${{ env.BACKEND_DIR }}
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password123
          PGDATABASE: flask_demo
          PGPORT: 5432

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Start backend server
        run: |
          export FLASK_APP=${{ env.BACKEND_DIR }}/app.py
          flask run --host=0.0.0.0 --port=5000 &
          echo "Waiting for backend to become healthy..."
          for i in {1..30}; do
            if curl -sSf http://localhost:5000/ > /dev/null; then
              echo "Backend is up"; break; fi; echo "...waiting"; sleep 2; done
        working-directory: ${{ env.BACKEND_DIR }}

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ${{ env.FRONTEND_DIR }}
        env:
          VITE_API_URL: http://localhost:5000

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ${{ env.FRONTEND_DIR }}/playwright-report/
          retention-days: 30
